name = "grafana-faro-proxy"
main = "worker.js"
compatibility_date = "2024-01-15"

[env.production.vars]
GRAFANA_COLLECTOR_HOST = "faro-collector-prod-us-east-0.grafana.net"
ALLOWED_ORIGINS = "https://michaellamb.dev,https://blog.michaellamb.dev,http://localhost:4000,http://127.0.0.1:4000"

# Development environment (optional)
[env.development.vars]
GRAFANA_COLLECTOR_HOST = "faro-collector-prod-us-east-0.grafana.net"  
ALLOWED_ORIGINS = "http://localhost:4000"

# Routes configuration
[[routes]]
pattern = "grafana.michaellamb.dev/faro-proxy*"
zone_name = "michaellamb.dev"