name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Cloudflare Workers
    steps:
      - uses: actions/checkout@v3
      
      # We'll set secrets directly in Cloudflare dashboard
      # and use wrangler only for deployment
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Wrangler
        run: npm install -g wrangler@latest
      
      - name: Deploy with Wrangler
        run: wrangler deploy --env production
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
