name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Cloudflare Workers
    steps:
      - uses: actions/checkout@v3
      
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production
          # Using wrangler v3 format for secrets
          preCommands: |
            echo "Adding secrets..."
            npx wrangler secret put BLOG_INGEST_TOKEN --env production <<< "${{ secrets.BLOG_INGEST_TOKEN }}"
            npx wrangler secret put LETTERBOXD_INGEST_TOKEN --env production <<< "${{ secrets.LETTERBOXD_INGEST_TOKEN }}"
