name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: Cloudflare Workers
    steps:
      - uses: actions/checkout@v3
      
      # We'll set secrets directly in Cloudflare dashboard
      # and use wrangler only for deployment
          
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3.1.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          preCommands: |
            echo "Checking Wrangler version"
            wrangler --version
            echo "Setting up authentication"
            echo "CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }}" > .env
            echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }}" >> .env
          command: publish
